import test from "node:test";
import assert from "node:assert/strict";
import { buildPluginRegistry } from "../dist/index.js";
import {
  PLUGIN_MAX_RNG_DRAWS,
  buildPluginExecutionRegistry,
  handleRegisteredPluginEvent,
  resolveRegisteredPluginAction
} from "../dist/backend-execution.js";

const range = { minInclusive: "1.0.0", maxExclusive: "2.0.0" };
function manifest() { return { schemaVersion:"1.0", pluginId:"dice", version:"1.0.0", engineApiRange:range, description:"test plugin", schemaVersions:[], dependencies:[], capabilityIds:["dice.capability.roll"], recipeIds:[], backend:{ blockTypeIds:[], actionTypeIds:["dice.action.roll"], scheduledEventTypeIds:["dice.event.react"], effectTypeIds:["dice.effect.private"] }, ui:null }; }
function world() { return { schemaVersion:"1.0", revision:0, clock:{elapsedSeconds:10}, locations:[{id:"room"}], entities:[{id:"hero",type:"person",status:"available",locationId:"room"}], resources:[{id:"energy",unit:"point",value:5,min:0,max:10}], items:[], terminal:null }; }
function rng(seed=7) { let draw=0; return { drawInt(maxExclusive) { const value=(seed+draw++)%maxExclusive; return { ok:true, value, provenance:{algorithm:"test-v1",seed,streamId:"test",drawIndex:draw-1,rawUint32:seed+draw-1,maxExclusive,value} }; } }; }
function validPlan(input, roll=null) { return { schemaVersion:"1.0", actionTypeId:input.actionTypeId, status:"executed", requestedUnits:1, completedUnits:1, durationSeconds:5, reasonCode:roll===null?null:`ROLL_${roll}`, effects:[{schemaVersion:"1.0",type:"resource.change",sourceId:input.actionTypeId,resourceId:"energy",delta:-1}], scheduledEvents:[] }; }
function executionRegistry(overrides={}) { const built=buildPluginRegistry([manifest()]); assert.equal(built.ok,true); const result=buildPluginExecutionRegistry(built.registry,[{pluginId:"dice",actionResolvers:[{actionTypeId:"dice.action.roll",validateArgs:(args)=>args&&typeof args==="object"&&!Array.isArray(args)&&args.units===1,resolve:(input)=>validPlan(input),...overrides.resolver}],schedulerHandlers:[{eventTypeId:"dice.event.react",handle:()=>[],...overrides.handler}]}]); assert.equal(result.ok,true); return result.registry; }

test("B08-02 execution registration must match installed manifest declarations",()=>{ const built=buildPluginRegistry([manifest()]); assert.equal(built.ok,true); const bad=buildPluginExecutionRegistry(built.registry,[{pluginId:"dice",actionResolvers:[{actionTypeId:"dice.action.hidden",validateArgs:()=>true,resolve:()=>({})}],schedulerHandlers:[]}]); assert.equal(bad.ok,false); assert.equal(bad.code,"ACTION_NOT_DECLARED"); });
test("B08-02 invalid args are rejected before resolver invocation",()=>{ let calls=0; const registry=executionRegistry({resolver:{resolve:(input)=>{calls+=1;return validPlan(input);}}}); const result=resolveRegisteredPluginAction({registry,actionTypeId:"dice.action.roll",state:world(),args:{units:2},rng:rng()}); assert.equal(result.ok,false); assert.equal(result.code,"INVALID_ARGS"); assert.equal(calls,0); });
test("B08-02 resolver receives detached deeply frozen state and args",()=>{ const original=world(); let observed=false; const registry=executionRegistry({resolver:{resolve(input){ observed=Object.isFrozen(input.state)&&Object.isFrozen(input.state.resources)&&Object.isFrozen(input.state.resources[0])&&Object.isFrozen(input.args); assert.notEqual(input.state,original); assert.throws(()=>{input.state.resources[0].value=999;},TypeError); return validPlan(input); }}}); const result=resolveRegisteredPluginAction({registry,actionTypeId:"dice.action.roll",state:original,args:{units:1},rng:rng()}); assert.equal(result.ok,true); assert.equal(observed,true); assert.equal(original.resources[0].value,5); });
test("B08-02 host owns deterministic RNG provenance",()=>{ const registry=executionRegistry({resolver:{resolve(input){const roll=input.rng.drawInt(6)+1;return validPlan(input,roll);}}}); const left=resolveRegisteredPluginAction({registry,actionTypeId:"dice.action.roll",state:world(),args:{units:1},rng:rng(13)}); const right=resolveRegisteredPluginAction({registry,actionTypeId:"dice.action.roll",state:world(),args:{units:1},rng:rng(13)}); assert.equal(left.ok,true); assert.equal(right.ok,true); assert.deepEqual(left.plan,right.plan); assert.equal(left.plan.rngTrace.length,1); assert.equal(Object.isFrozen(left.plan.rngTrace),true); });
test("B08-02 resolver throws and RNG draw overflow fail without plan",()=>{ const thrown=executionRegistry({resolver:{resolve(){throw new Error("boom");}}}); assert.deepEqual(resolveRegisteredPluginAction({registry:thrown,actionTypeId:"dice.action.roll",state:world(),args:{units:1},rng:rng()}),{ok:false,code:"RESOLVER_FAILED"}); const overflowing=executionRegistry({resolver:{resolve(input){for(let i=0;i<=PLUGIN_MAX_RNG_DRAWS;i+=1)input.rng.drawInt(2);return validPlan(input);}}}); const overflow=resolveRegisteredPluginAction({registry:overflowing,actionTypeId:"dice.action.roll",state:world(),args:{units:1},rng:rng()}); assert.equal(overflow.ok,false); assert.equal(overflow.code,"RNG_DRAW_LIMIT_EXCEEDED"); });
test("B08-02 authority-widened and custom-effect plans fail closed",()=>{ const widened=executionRegistry({resolver:{resolve(input){return{...validPlan(input),candidateState:world()};}}}); assert.equal(resolveRegisteredPluginAction({registry:widened,actionTypeId:"dice.action.roll",state:world(),args:{units:1},rng:rng()}).code,"INVALID_PLAN"); const custom=executionRegistry({resolver:{resolve(input){return{...validPlan(input),effects:[{schemaVersion:"1.0",type:"dice.effect.private",sourceId:input.actionTypeId,value:1}]};}}}); assert.equal(resolveRegisteredPluginAction({registry:custom,actionTypeId:"dice.action.roll",state:world(),args:{units:1},rng:rng()}).code,"INVALID_PLAN"); });
test("B08-02 blocked plans cannot hide time/effects/events and must explain why",()=>{ const registry=executionRegistry({resolver:{resolve(input){return{...validPlan(input),status:"blocked",completedUnits:0,durationSeconds:5,reasonCode:"NOPE"};}}}); const result=resolveRegisteredPluginAction({registry,actionTypeId:"dice.action.roll",state:world(),args:{units:1},rng:rng()}); assert.equal(result.ok,false); assert.equal(result.code,"INVALID_PLAN"); });
test("B08-02 public readonly registry never leaks mutable backing Map through forEach",()=>{ const registry=executionRegistry(); registry.actionResolvers.forEach((_value,_key,map)=>{ assert.equal(map,registry.actionResolvers); assert.equal(typeof map.set,"undefined"); }); assert.equal(registry.actionResolvers.size,1); });
test("B08-02 scheduler handler receives frozen snapshot and may only emit its own-source canonical events",()=>{ let frozen=false; const registry=executionRegistry({handler:{handle(input){ frozen=Object.isFrozen(input.state)&&Object.isFrozen(input.event)&&Object.isFrozen(input.context); return[{schemaVersion:"1.0",eventId:"child-1",atElapsedSeconds:12,order:10,sourceId:input.eventTypeId,kind:"core.marker",payload:{markerId:"rolled"}}]; }}}); const event={schemaVersion:"1.0",eventId:"parent-1",atElapsedSeconds:11,order:10,sourceId:"dice.action.roll",kind:"core.marker",payload:{markerId:"parent"}}; const result=handleRegisteredPluginEvent({registry,eventTypeId:"dice.event.react",event,state:world(),context:{sequence:0,effectiveOrder:10,intervalEndElapsedSeconds:20},rng:rng()}); assert.equal(result.ok,true); assert.equal(frozen,true); assert.equal(result.events[0].sourceId,"dice.event.react"); const foreign=executionRegistry({handler:{handle(){return[{schemaVersion:"1.0",eventId:"child-2",atElapsedSeconds:12,order:10,sourceId:"core.paint",kind:"core.marker",payload:{markerId:"bad"}}];}}}); const rejected=handleRegisteredPluginEvent({registry:foreign,eventTypeId:"dice.event.react",event,state:world(),context:{sequence:0,effectiveOrder:10,intervalEndElapsedSeconds:20},rng:rng()}); assert.equal(rejected.ok,false); assert.equal(rejected.code,"INVALID_GENERATED_EVENTS"); });
