import assert from "node:assert/strict";
import { execFile as execFileCallback } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { promisify } from "node:util";
import test from "node:test";
import { createBuilderWorkspacePolicy, BuilderPolicyError } from "../dist/workspace-policy.js";
import { runBoundedAgentJob } from "../dist/bounded-agent-job.js";
import { MutableWorkspaceError, createMutableBuilderWorkspace, createPolicyVerificationRunner } from "../dist/workspace-executor.js";

const execFile = promisify(execFileCallback);

async function git(args, cwd) {
  const { stdout } = await execFile("git", args, { cwd, windowsHide: true });
  return stdout.trim();
}

async function fixtureRepository() {
  const root = await mkdtemp(join(tmpdir(), "builder-agent-job-fixture-"));
  const source = join(root, "source");
  await mkdir(source);
  await git(["init", "--initial-branch=main"], source);
  await git(["config", "user.email", "builder-test@example.invalid"], source);
  await git(["config", "user.name", "Builder Test"], source);
  await mkdir(join(source, "allowed"));
  await writeFile(join(source, "allowed", "module.txt"), "version 1\n", "utf8");
  await git(["add", "."], source);
  await git(["commit", "--quiet", "-m", "fixture"], source);
  const sha = await git(["rev-parse", "HEAD"], source);
  return { root, source, sha };
}

test("B13.a2 bounded agent job applies patch and runs only policy verification commands", async (t) => {
  const fixture = await fixtureRepository();
  t.after(() => rm(fixture.root, { recursive: true, force: true }));

  const policy = createBuilderWorkspacePolicy({
    repositoryId: "owner/project",
    repositoryRoot: fixture.source,
    baseBranch: "main",
    baseCommitSha: fixture.sha,
    readablePaths: ["allowed"],
    writablePaths: ["allowed"],
    verificationCommands: [{ executable: "git", args: ["status", "--porcelain"] }]
  });

  const workspace = await createMutableBuilderWorkspace(policy);
  t.after(() => workspace.dispose());

  const result = await runBoundedAgentJob(
    workspace,
    policy,
    [{ path: "allowed/generated.txt", content: "generated by agent\n" }],
    {
      run: (executable, args) => createPolicyVerificationRunner(policy).run(workspace.workspaceRoot, executable, args)
    }
  );

  assert.deepEqual(result.patch.changedPaths, ["allowed/generated.txt"]);
  assert.match(result.patch.diffHash, /^[0-9a-f]{64}$/);
  assert.match(result.patch.treeHash, /^[0-9a-f]{40}$/);
  assert.deepEqual(result.verifiedCommands, ["git status --porcelain"]);
  assert.equal(await workspace.readText("allowed/generated.txt"), "generated by agent\n");
  assert.equal(await readFile(join(fixture.source, "allowed", "module.txt"), "utf8"), "version 1\n");
});

test("B13.a2 agent job fails closed when a patch path is outside the policy", async (t) => {
  const fixture = await fixtureRepository();
  t.after(() => rm(fixture.root, { recursive: true, force: true }));

  const policy = createBuilderWorkspacePolicy({
    repositoryId: "owner/project",
    repositoryRoot: fixture.source,
    baseBranch: "main",
    baseCommitSha: fixture.sha,
    readablePaths: ["allowed"],
    writablePaths: ["allowed"],
    verificationCommands: [{ executable: "git", args: ["status", "--porcelain"] }]
  });

  const workspace = await createMutableBuilderWorkspace(policy);
  t.after(() => workspace.dispose());

  await assert.rejects(
    runBoundedAgentJob(
      workspace,
      policy,
      [{ path: "escape.txt", content: "no\n" }],
      { async run() { throw new Error("must not run"); } }
    ),
    (error) => error instanceof BuilderPolicyError && error.code === "path_not_allowed"
  );
});
